---
timer: 'H H * * *'
parameters: []
provision:
  os: "fedora"
  stage: "bare"
  provider: "aws"
actions:
  - type: "host_script"
    title: "install CI user account"
    script: |-
      oct prepare user
      sed -i 's/User ec2-user/User origin/g' ./.config/origin-ci-tool/inventory/.ssh_config
  - type: "script"
    title: "update bad vim"
    script: |-
      sudo dnf update -y vim-minimal
  - type: "host_script"
    title: "install base dependencies"
    script: |-
      oct prepare dependencies
  - type: "host_script"
    title: "install golang"
    script: |-
      oct prepare golang --version '1.8.3' --repourl 'https://cbs.centos.org/repos/paas7-openshift-origin37-candidate/x86_64/os/'
  - type: "host_script"
    title: "prepare repositories"
    script: |-
      oct prepare repositories
  - type: "script"
    title: "install system accounting rules"
    script: |-
      cat <<CONF >origin-ami-accounting.conf
      [Manager]
      DefaultCPUAccounting=yes
      DefaultMemoryAccounting=yes
      CONF
      sudo mkdir -p /etc/systemd/system.conf.d/
      sudo mv origin-ami-accounting.conf /etc/systemd/system.conf.d/
      sudo systemctl daemon-reexec
  - type: "script"
    title: "set up cri-o repository"
    script: |-
      mkdir -p /data/src/github.com/kubernetes-incubator
      cd /data/src/github.com/kubernetes-incubator
      git clone https://github.com/kubernetes-incubator/cri-o.git
      cd cri-o
      git fetch origin pull/927/head:pull
      git merge pull
  - type: "script"
    title: "set up cri-o dependencies"
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags setup  \
                       --become-user root \
                       --connection local \
                       /data/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/main.yml
  - type: "host_script"
    title: "package the AMI"
    script: |-
      oct package ami --stage=crio
  - type: "host_script"
    title: "release the AMI"
    script: |-
      oct package ami --mark-ready
artifacts: []
generated_artifacts:
  installed_packages.log: 'sudo yum list installed'
  avc_denials.log: 'sudo ausearch -m AVC -m SELINUX_ERR'
  filesystem.info: 'sudo df -h && sudo pvs && sudo vgs && sudo lvs'
system_journals:
  - crio.service
