---
parent: 'common/test_cases/origin_release_install_gce.yml'
overrides:
  junit_analysis: False
  email:
    - ccoleman@redhat.com
extensions:
  parameters:
    - name: buildId
      description: "Unique build number for each run."
    - name: REPO_OWNER
      description: "GitHub org that triggered the job."
      default_value: openshift
    - name: REPO_NAME
      description: "GitHub repo that triggered the job."
      default_value: origin
    - name: PULL_BASE_REF
      description: "Ref name of the base branch."
    - name: PULL_BASE_SHA
      description: "Git SHA of the base branch."
    - name: PULL_REFS
      description: "All refs to test."
    - name: PULL_NUMBER
      description: "Pull request number."
    - name: PULL_PULL_SHA
      description: "Pull request head SHA."
    - name: SUITE
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> di
rectory to run."
      default_value: "conformance-k8s"
