---
parameters:
  - name: buildId
    description: "Unique build number for each run."
  - name: REPO_OWNER
    description: "GitHub org that triggered the job."
  - name: REPO_NAME
    description: "GitHub repo that triggered the job."
  - name: PULL_BASE_REF
    description: "Ref name of the base branch."
  - name: PULL_BASE_SHA
    description: "Git SHA of the base branch."
  - name: PULL_REFS
    description: "All refs to test."
  - name: PULL_NUMBER
    description: "Pull request number."
  - name: PULL_PULL_SHA
    description: "Pull request head SHA."
provision:
  os: "fedora"
  stage: "bare"
  provider: "aws"
actions:
  - type: "host_script"
    title: "install CI user account"
    script: |-
      oct prepare user
      sed -i 's/User ec2-user/User origin/g' ./.config/origin-ci-tool/inventory/.ssh_config
  - type: "script"
    title: "update bad vim"
    script: |-
      sudo dnf update -y vim-minimal
  - type: "host_script"
    title: "install base dependencies"
    script: |-
      oct prepare dependencies
  - type: "host_script"
    title: "install golang"
    script: |-
      oct prepare golang --version '1.8.3' --repourl 'https://cbs.centos.org/repos/paas7-openshift-origin37-candidate/x86_64/os/'
  - type: "host_script"
    title: "prepare repositories"
    script: |-
      oct prepare repositories
  - type: "script"
    title: "install system accounting rules"
    script: |-
      cat <<CONF >origin-ami-accounting.conf
      [Manager]
      DefaultCPUAccounting=yes
      DefaultMemoryAccounting=yes
      CONF
      sudo mkdir -p /etc/systemd/system.conf.d/
      sudo mv origin-ami-accounting.conf /etc/systemd/system.conf.d/
      sudo systemctl daemon-reexec
  - type: "forward_parameters"
    parameters:
      - PULL_NUMBER
      - PULL_BASE_SHA
      - PULL_PULL_SHA
  - type: "script"
    title: "clone cri-o and check out the correct refs"
    script: |-
      cd /data/src/github.com/kubernetes-incubator/cri-o
      git fetch origin
      git branch target "${PULL_BASE_SHA}"
      git checkout target
      git fetch origin "pull/${PULL_NUMBER}/head:pr"
      git merge "${PULL_PULL_SHA}"
  - type: "script"
    title: "set up cri-o dependencies"
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags setup  \
                       --become-user root \
                       --connection local \
                       /data/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/main.yml
  - type: "host_script"
    title: "package the AMI"
    script: |-
      oct package ami --stage=crio --tag=pr="${PULL_NUMBER}"
  - type: "script"
    title: "run the cri-o tests"
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags integration,e2e \
                       --become-user root \
                       --connection local \
                       /data/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/main.yml
post_actions:
  - type: "script"
    title: "gather cri-o test output"
    script: |-
      if [[ ! -s /data/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/results.yml ]]; then
        echo "Skipping, no results playbook found."
        exit 0
      fi
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags e2e    \
                       --become-user root \
                       --connection local \
                       /data/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/results.yml
artifacts:
  - /data/src/k8s.io/kubernetes/artifacts
  - /data/src/k8s.io/kubernetes/e2e.log
  - /tmp/artifacts
  - /tmp/kubelet.log
  - /tmp/kube-apiserver.log
  - /tmp/kube-controller-manager.log
  - /tmp/kube-proxy.log
  - /tmp/kube-proxy.yaml
  - /tmp/kube-scheduler.log
generated_artifacts:
  installed_packages.log: 'sudo yum list installed'
  avc_denials.log: 'sudo ausearch -m AVC -m SELINUX_ERR -m USER_AVC'
  filesystem.info: 'sudo df -h && sudo pvs && sudo vgs && sudo lvs'
  pid1.journal: 'sudo journalctl _PID=1 --no-pager --all --lines=all'
system_journals:
  - crio.service
  - customcluster.service